kind: pipeline
type: docker
name: default
steps:
  - name: Build Image
    image: plugins/docker
    settings:
      registry: https://repo.smartsheep.studio
      repo: repo.smartsheep.studio/atom/matrix
      use_cache: true
      username: Drone
      password: Drone@2007
      auto_tag: true
    when:
      event: push
      branch: master
