kind: pipeline
type: docker
name: default
steps:
  - name: build image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      registry: https://code.smartsheep.studio
      repo: code.smartsheep.studio/atom/matrix
      username: Drone
      password: Drone@2007
      auto_tag: true
    when:
      ref:
      - refs/heads/master
      - refs/tags/*
      event: 
      - push
      - pull_request
      - tag
      branch: master
