[general]
instance_id = "86ad4f61-8bff-4bf8-9a93-8da7813a722c"
base_url = "http://localhost:9446"
endpoints = "http://localhost:9443"
mount_key = "WGqNUFNhED"

[resources]
user_contents = "../resources/uploads"

[security]
sessions_alive_duration = "720h"

[http]
prefork = false
listen_address = ":"
listen_port = 9446
max_body_size = 4194304

[datasource]
dsn = "host=localhost user=postgres password=password dbname=atom port=5432 sslmode=disable timezone=Asia/Shanghai"